# Generated by Django 2.1.2 on 2018-10-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181019_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='comuna',
        ),
    ]
