# Generated by Django 2.1.2 on 2018-10-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_region_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[(1, 'Macho'), (2, 'Hembra')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
