# Generated by Django 2.1.1 on 2018-11-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181026_1938'),
        ('core', '0005_auto_20181026_2119'),
    ]

    operations = [
    ]
